%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Peter\Dropbox\NovimData.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 01-Jul-2019 14:48:27
clear;
%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 34);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "E2:AL19";

% Specify column names and types
opts.VariableNames = ["VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38"];
opts.SelectedVariableNames = ["VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
NovimData = readtable("C:\Users\Peter\Dropbox\NovimData.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
Coal=table2array(NovimData(1,1:34));
Petrol=table2array(NovimData(2,1:34));
NatGas=table2array(NovimData(3,1:34));
Nuc=table2array(NovimData(4,1:34));
Wind=table2array(NovimData(6,1:34));
Solar=table2array(NovimData(7,1:34));
Hydro=table2array(NovimData(8,1:34));
Other=table2array(NovimData(9,1:34));
Total=table2array(NovimData(10,1:34));

%percents
CoalP=Coal./Total;
PetrolP=Petrol./Total;
GasP=NatGas./Total;
NucP=Nuc./Total;
WindP=Wind./Total;
SolarP=Solar./Total;
HydroP=Hydro./Total;
OtherP=Other./Total;
plot(CoalP)
hold on
plot(PetrolP)
plot(GasP)
plot(NucP)
plot(WindP)
plot(SolarP)
plot(HydroP)
plot(OtherP)
legend('Coal','Petrol','Gas','Nuclear','Wind','Solar','Hydro','Other')
ylabel('Fraction of Total Net Electricity Generation')
xlabel('Years past 2016')
title('Total Energy makeup of US Grid as a function of time')
%%Price Data (https://www.eia.gov/electricity/annual/html/epa_08_04.html) 2017 Data
PriceCoal=table2array(NovimData(11,1:34)); %In (cents/KWh)
PriceGas=table2array(NovimData(13,1:34));
PriceWind=table2array(NovimData(15,1:34));
PriceSolar=table2array(NovimData(16,1:34));
PriceNuc=table2array(NovimData(14,1:34));
PriceHyrdo=table2array(NovimData(17,1:34));
PricePetrol=table2array(NovimData(12,1:34));
PriceOther=table2array(NovimData(18,1:34)); %?
Markup=13.19/2.97218355244905; %https://www.electricchoice.com/electricity-prices-by-state/
PriceKWh=(PriceCoal.*CoalP+PriceGas.*GasP+PriceWind.*WindP+PriceSolar.*SolarP+PriceNuc.*NucP+PriceHyrdo.*HydroP+PricePetrol.*PetrolP+PriceOther.*OtherP)*Markup;
figure
plot(PriceKWh)%Need to predict price changes in SS Data
ylabel('Average Consumer Price of Energy in US')
xlabel('Years past 2016')
title('Price of US Energy over time')
%%
%%Converted CO2 per KW/h using Total US Total electric power data from 2017 (https://www.eia.gov/tools/faqs/faq.php?id=74&t=11)
CoalCO2=CoalP*(1226559558/1205835275); %In units of Metric tons CO2/KWh
NatGasCO2=GasP*(585493677/1296414692); %In units of Metric tons CO2/KWh
PetrolCO2=PetrolP*(23399618/21389958); %In units of Metric tons CO2/KWh
OtherCO2=OtherP*(13878137/13094027); %In units of Metric tons CO2/KWh
%pie([CoalCO2/(CoalCO2+NatGasCO2+PetrolCO2+OtherCO2) NatGasCO2/(CoalCO2+NatGasCO2+PetrolCO2+OtherCO2) PetrolCO2/(CoalCO2+NatGasCO2+PetrolCO2+OtherCO2) OtherCO2/(CoalCO2+NatGasCO2+PetrolCO2+OtherCO2)],{'Coal','Gas','Petrol','Other'})
CO2KWh=CoalCO2+NatGasCO2+PetrolCO2+OtherCO2; %Total CO2 per KWh
TotalCO2=(Total.*CO2KWh)/(10^3)*(1/.14); %Total CO2 Emissions in Gigatons
%%
%%Converted CO2 to ppm and ppm to temp
CO2ppm=TotalCO2./7.81; %Units in ppm increase/year (https://skepticalscience.com/print.php?r=45)
figure
plot(CO2ppm)
ylabel('Increase of CO2(ppm/year)')
xlabel('Years past 2016')
title('Increase of CO2 ppm into the atmosphere as a function of time')
figure
plot(Total)
xlabel('Years past 2016')
ylabel('Total kWH used per year')
title('Total KWh used as a function of time')
TempCurrent=zeros(1,34);
TempCurrent(1)=288.15;
CO2Current=zeros(1,35);
CO2Current(1)=405;
for i=2:35
CO2Current(i)=405+sum(CO2ppm(1:i-1));
dT(i-1)=1.66*log(CO2Current(i)/CO2Current(1));
dTB(i-1)=1.66*log(CO2Current(i)/CO2Current(i-1));
end
%Calculate heat feedback (http://globalwarmingequation.info/calc%20temperature%20increase.pdf)
P0=1315.86;
for j=1:34
for k=1:15
P=P0*exp(-(43655/8.3145)*((1/(TempCurrent(j)+dT(j)))-(1/TempCurrent(j))));
dP(k)=P-P0;
dTau=.00634*(dP(k)/(P0^.497));
dT2(k)=32.09*dTau;
dT(j)=dT2(k);
end
feedbackloop(j)=sum(dT2);
TempCurrent(j+1)=TempCurrent(j)+dTB(j)+feedbackloop(j);
dT2(1:34)=0;
end
(TempCurrent(34)-TempCurrent(1))
plot(TempCurrent)
title('Total Increase in Temp as a function of time given current US sectors')
xlabel('Years past 2016')
ylabel('Average Temp (K)')
plot(feedbackloop)